var ABERTURA = "0";
var INICIO = "5";
var ENCERRADO = "37";

var AP_RH_VERIFICACAO = "127";
var AP_CENTRO_CUSTO_ATUAL = "6";
var AP_CENTRO_CUSTO_DESTINO = "16";
var AP_PLANJ_CONTR_ORC = "10";
var AP_DIRETORIA = "13";
var AP_DIRETORIA_GRL = "84";
var ASS_FUNCIONARIO = "39";
var AP_RH_VALIDACAO = "29";
var AJUSTAR = "65";

var INTEGR_PROTHEUS = "32";
var TRAT_ERRO_INTEGR_PROT = "34";
